import type { Metadata } from "next";
import { Quantico, Rubik } from "next/font/google";
import "./globals.css";


/* Load Google Fonts */
const quantico = Quantico({
  variable: "--font-quantico",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Nexa Developments LTD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quantico.variable} ${rubik.variable} antialiased`}>
        <div suppressHydrationWarning>
         
          {children}
          
        </div>
      </body>
    </html>
  );
}
